### ISSUE TITLE
Missing 11pm-00am slot on DST

### ISSUE THREAD

**Issue by ccristal** [lozzd/octopus-energy-rates-card#18]
During Daylight Saving Time, the card only shows rates until 11PM. That's because, being the Octopus Integration rates published in UTC, you need to fetch one hour from tomorrow's rates in order to fill today's 11PM-00AM slot.
![image](https://github.com/lozzd/octopus-energy-rates-card/assets/5416417/439be893-9949-421f-993e-e228505b063a)

**Comment by lozzd** [comment]
The card was showing you rates until 10:30-11 slot because that's all Octopus publishes, it's not a timezone thing. If you check the website, you'll notice they end at 11pm there too. (e.g. now the card should be showing up until Sunday at 11pm - shown as 22:30 in the card)
