### ISSUE TITLE
No rates on Octopus import Sensor after update to - Octopus API and Octopus Energy Integration

### ISSUE THREAD

**Issue by dannyhicko** [lozzd/octopus-energy-rates-card#19]
Hi, just to say first of all, I love the rates card. Its great to have on in HA. So many thanks.

I think it might have stopped working after an update to Bottle cap Dave's integration, that I think was forced by the Octopus API update?

Lovelace custom card - v0.1.4

Home Assistant Octopus Energy - v8.0.0

It all looks good I think?

entity: sensor.octopus_energy_current_rate
type: custom:octopus-energy-rates-card
cols: 2
showday: true
showpast: false

![image](https://github.com/lozzd/octopus-energy-rates-card/assets/11241258/df24e09d-237d-4946-bf40-0dfb3d357bb6)

![image](https://github.com/lozzd/octopus-energy-rates-card/assets/11241258/2e55cf3c-7c14-477a-9272-fb9798e057ba)

Many thanks in advance for any info.

**Comment by jamesog** [comment]
I found the same thing earlier. I've opened #20 which fixes it for me.

**Comment by dannyhicko** [comment]
Ahh great thanks I will look at your request.

**Comment by lozzd** [comment]
Thanks to @jamesog this should now be resolved in release v0.2.0. Apologies if you haven't yet updated to 8.0.0 of Dave's integration, it's not backwards compatible. Update both the card and the integration together when you're ready.
