### ISSUE TITLE
Stopped working following update 

### ISSUE THREAD

**Issue by Redding43** [lozzd/octopus-energy-rates-card#21]
Unsure whether it is my config but this has stopped working after the latest update of HA Core and the latest version of this card. ‘There are no rates assigned to that entity’

**Comment by lozzd** [comment]
Sorry, there was a breaking change on the Octopus Energy integration. You'll need to update to 8.0+ and restart HA and it should work again

**Comment by Redding43** [comment]
Thanks, I’m just waiting for a Predbat fix and then will update the Octopus integration

**Comment by CharlieTemplar** [comment]
is there more than the js to update?  updated to octopus integration to 8.1 and manually changed  `octopus-energy-rates-card.js`
Restarted HA and the apex chart which I also had to update config for is all working using same entity
Downloaded the js update from here and compared, it's identical...
![image](https://github.com/lozzd/octopus-energy-rates-card/assets/47461175/4db7b7fb-d574-4d95-b25c-a12b294f29e4)

**Comment by bry25uk** [comment]
I too still have the same issue?
![Capture](https://github.com/lozzd/octopus-energy-rates-card/assets/53639368/0ccb9310-60f2-4b92-826d-c9e17059583a)

Home Assistant 2023.8.3
Supervisor 2023.08.1
Operating System 10.4
Frontend 20230802.1 - latest

OCTOPUS ENERGY : [8.1.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/compare/v8.0.0...v8.1.0) (2023-08-12)

**Comment by lozzd** [comment]
And you have the latest version of the card?
I haven't updated to 8.1 yet, I hope it didn't change format again (can anyone else confirm if theirs is working on that version?)

**Comment by CharlieTemplar** [comment]
> I too still have the same issue? ![Capture](https://user-images.githubusercontent.com/53639368/261790158-0ccb9310-60f2-4b92-826d-c9e17059583a.JPG)
> 
> Home Assistant 2023.8.3 Supervisor 2023.08.1 Operating System 10.4 Frontend 20230802.1 - latest
> 
> OCTOPUS ENERGY : [8.1.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/compare/v8.0.0...v8.1.0) (2023-08-12)

Oh, fixed mine but because this is a js and I installed manually had to clear the browser cache and restart the HA a few times before the changes took.  Then had to clear the cache on the HA android app and every other device pointing to this, but all working now...

**Comment by slip83** [comment]
I now have blank widgets after updating octopus to v9.0.1 
I wonder if anyone else encounter the same and if there is a fix?

**Comment by lozzd** [comment]
Fixed in v0.3.0, see #27
