### ISSUE TITLE
Support for different time periods

### ISSUE THREAD

**Issue by VovaBre** [lozzd/octopus-energy-rates-card#23]
The card is great, however for those on Octopus Tracker tariff the current rate changes only once a day (at least for those without Home mini) - it would be great to be able to change half hourly updates to hourly / daily through variable

**Comment by airampg** [comment]
I would like to support @VovaBre's request. For example, we have gas on tracker and electricity on agile. This card would work greatly to show the price for the day as well. I could suggest, as a workaround, to allow to limit the number of hours that are shown at once. That way, if we could limit the hours to 1 hour, we would have the price of the day. Currently, if I attempt to show my gas prices, I get the same one repeated multiple times every half hour.

**Comment by lozzd** [comment]
I believe a feature was added in 0.3.0 which might help you here: combinerate (see the README) removes duplicate rows, so I think it would colapse the card down.
Try it and let us know!
