### ISSUE TITLE
Support for Octopus target sensors

### ISSUE THREAD

**Issue by Nurgus** [lozzd/octopus-energy-rates-card#29]
Any chance of this card being adapted to use the time/rate information in the attributes of one or more target sensors? If it could merge several target sensors together that would be even better.

It would be a great way to visualise what the target sensors are actually doing.

Also related question: Allow target sensors as an optional argument and use them to colour the time slots.

**Comment by lozzd** [comment]
Thanks to @alfwro13 this has been released in v0.4.0. You can now point to the target sensor and the rows are coloured.
