### ISSUE TITLE
Flux

### ISSUE THREAD

**Issue by steve-prentice** [lozzd/octopus-energy-rates-card#30]
Hello! I'm on Flux rather than Agile, but it'd still be cool for the card to show the more simple rates... is that easy? :)
I'm not sure on how to go about doing that. So far I have this:

entity: sensor.octopus_energy_electricity_**_current_rate
type: custom:octopus-energy-rates-card
cols: 1
showday: false
showpast: false
title: Octopus Flux
hour12: false

Which gets me the data etc... but as Flux time periods aren't every 30 mins I don't need all the time slots showing... is that a possibility to change?

Cheap 02:00 - 05:00
Expensive 16:00 - 19:00
Normal All other times

Thanks!

**Comment by lozzd** [comment]
I believe a feature was added in 0.3.0 which might help you here: `combinerate` (see the README) removes duplicate rows, so I think it would colapse the card down. 
Try it and let us know!

**Comment by steve-prentice** [comment]
Hey lozzd, thank you so much, apols I hadn't spotted your reply... just tried that and yes, that works a treat! Ideal, thanks! :-)
