### ISSUE TITLE
I have upgraded to 9.0.0 on BottleCapDave's update and now the charts no longer work

### ISSUE THREAD

**Issue by UK-JustinSmall** [lozzd/octopus-energy-rates-card#32]
I raised a issue on Bottlecap Dave's github and he has suggested I raise this here as there appears to be a issue with the card

https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/547

**Comment by lozzd** [comment]
Correct, please see issue #27 
Downgrade back to 8.x and it will work for now

**Comment by UK-JustinSmall** [comment]
I removed 9.0.0 and installed 8.5.2 and still get the error

**Comment by alfwro13** [comment]
> I removed 9.0.0 and installed 8.5.2 and still get the error

 it would appear that downgrade is not working - I have the same issue
