### ISSUE TITLE
No Rates Assigned

### ISSUE THREAD

**Issue by hotnuts21** [lozzd/octopus-energy-rates-card#4]
HI, I've installed your card tonight after running BottleCapDaves Octopus integration for a few days.  Ive set up a custom dashboard with your card and an entity list of the Octopus sensors.  But the energy rates card just shows no rates assigned, even though I copied the sensor id directly from the card below it which is showing data.  Maybe im missing something.  Screenshot attached.

I'm new to HA, so haven't had a chance to find all the logs, but nothing appears to be appearing in the main log.
I've attached an image so you can see.
![Energy-2-–-Home-Assistant](https://user-images.githubusercontent.com/5470425/216845894-b8ded6f4-a1bf-4dfe-978b-567ee9bea21b.png)

**Comment by lozzd** [comment]
Well that's odd. 
If you click on the "Current Rate" in your example above and it opens the history, can you expand "Attributes" and see if there's a long section titled `rates` in there?

**Comment by hotnuts21** [comment]
![Screenshot_20230205-212611](https://user-images.githubusercontent.com/5470425/216847277-be5aef98-93e9-438a-bca2-1f5fcec33258.png)

No and I just checked the tarrif and it's not right either, so for whatever reason I think the issue is with Dave's integration not your card.  It's obviously pulled in some rates at some point and then not updated. 

Apologies for wasting your time.

**Comment by lozzd** [comment]
Ah yeah... That appears to have stopped working 😬 
No worries hopefully it's an easy fix!
