### ISSUE TITLE
You need to define an entity

### ISSUE THREAD

**Issue by NickBeswick** [lozzd/octopus-energy-rates-card#41]
I get this error then adding the card with the following YAML:

type: custom:octopus-energy-rates-card
entity: event.octopus_energy_electricity_20e002xxxx_164000006xxxx_current_day_rates
cols: 2
showday: true
showpast: false

Can anyone assist ?

**Comment by igloo32** [comment]
In the latest releases due to changes where this gets it data from you need to update your config, "entity:" is now "currentEntity" and if you want to see tomorrows prices you also need to specific futureEntity, based on your config above, you now need this:

type: custom:octopus-energy-rates-card
currentEntity: event.octopus_energy_electricity_20e002xxxx_164000006xxxx_current_day_rates
futureEntity: event.octopus_energy_electricity_20e002xxxx_164000006xxxx_next_day_rates
cols: 2
showday: true
showpast: false

**Comment by igloo32** [comment]
Config is case sensitive,
"CurrentEntity:" should start with a lowercase "c" as per the readme, I.e. "currentEntity:"

**Comment by tony-park** [comment]
Thanks Igloo, that sorted it. Simple things!! 👍

**Comment by tony-park** [comment]
Hi,

any thoughts on how I can get the full period of data to display? ie up to 10:30pm the following night? At present, the card is displaying to 11:30pm today.

Thanks again

**Comment by NickBeswick** [comment]
> I get this error then adding the card with the following YAML:
> 
> type: custom:octopus-energy-rates-card entity: event.octopus_energy_electricity_20e002xxxx_164000006xxxx_current_day_rates cols: 2 showday: true showpast: false
> 
> Can anyone assist ?

I'm working now.  Thanks for the help @igloo32

**Comment by Ianknx** [comment]
Help please rates card.

Hi

I have tried over the past week to try and install on a dashboard, I keep getting type: custom:octopus-energy-rates-card and cannot continue from there.

any advice please.

**Comment by swests** [comment]
@Ianknx  - have you completely followed the instructions in the readme? Installed and have working the [BottlecapDave/HomeAssistant-OctopusEnergy](https://github.com/BottlecapDave/) component.  Installed this component via HACS? Added a component on a dashboard (by adding a manual card, and copying in the sample YAML in the readme (you do need to change the YAML to add your octopus details - again in the readme)

**Comment by Ianknx** [comment]
Hi
Many thanks for your reply.

I have Agile and cannot seem to set the target hours.

please see the attached  screenshot.

Thanks

**Comment by swests** [comment]
This card only displays the rates

**Comment by Ianknx** [comment]
Yes I understand that but the set up will not accept the times set, I have
copied  and pasted from the set up page but still not being accepted as per
my photograph or am I missing something.

I do appreciate your assistance thanks.

**Comment by swests** [comment]
There is no linked image.  You should try adding the image via github rather than from email (if that's what you're doing)

**Comment by Ianknx** [comment]
Ok, I will do that.

**Comment by Ianknx** [comment]
![octo](https://github.com/user-attachments/assets/11f7910b-f993-4bbe-bb6b-acf767b6b0cf)

**Comment by swests** [comment]
This is the wrong forum.  You issue with with the BottlecapDave Octopus Energy integration not this, the rates card.

I don't use this feature but that field isn't a time, it's a number of hours of you need in the target window.  I suggest you move the question over to  https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy and also read https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/setup/target_rate/
