### ISSUE TITLE
Can't read target rates (black on blue)

### ISSUE THREAD

**Issue by dan1elhughes** [lozzd/octopus-energy-rates-card#47]
In light mode, the time slots are not legible as the text is black on a navy background 🫣

<img width="511" alt="image" src="https://github.com/lozzd/octopus-energy-rates-card/assets/9041370/eaf3ebe7-003e-4120-82e7-937d7ddeb927">

**Comment by alfwro13** [comment]
I have submitted fix for this issue

**Comment by corvus2606** [comment]
This is fixed as of v0.5.1
