### ISSUE TITLE
not working even with current on bottlecapdaves v9.1 and v0.4.1

### ISSUE THREAD

**Issue by davidb187** [lozzd/octopus-energy-rates-card#49]
I'm beaten... using latest version bottlecapdaves with 0.41 and still getting "You need to define an entity" 

events are activated and I can see the attributes data with dates/times and inc_vat prices etc..

Any ideas?

type: custom:octopus-energy-rates-card
currentEntity: event.octopus_energy_electricity_z18q1XXX_190002404XXXX_current_day_rates
futureEntity: event.octopus_energy_electricity_z18q1XXXX_190002404XXXX_next_day_rates
cols: 3
hour12: false
showday: false
showpast: false
title: Octopus Import - p/kWh
unitstr: ''
lowlimit: 6
mediumlimit: 15
highlimit: 27
cheapest: true
multiplier: 100

**Comment by stevetrease** [comment]
Try to stripping the card back to the bare minimum:
Just the type and currentEntity config entries.

If that doesn't work, maybe try to rule out having an old version of the octopus-energy-rates-card installed. 
What happens if you use the old style plain "entity" entry?

**Comment by davidb187** [comment]
Hi - thanks - tried your suggestion ... the system  was using the old javascipt....

Turns out it was being cached in the browser - purging the chrome browser cache loaded up the new script and all is now good once more . 

I new it would be something stupid...

**Comment by ssegruts** [comment]
I have the same problem, cleared cache etc and still no joy.
Any help or advice appreciated

Pete

**Comment by deadphill** [comment]
Having the same issue.

Chosen the rates card, entered the following (as suggested earlier in the thread) but still get an error:

type: custom:octopus-energy-rates-card
currentEntity: event.octopus_energy_electricity_16pxxxxxxx_101xxxxxxxxxx_current_day_rates

Gives me this error: 

![image](https://github.com/lozzd/octopus-energy-rates-card/assets/81317059/31302877-be39-4c4d-9659-7e01d1efd0b2)

**Comment by lozzd** [comment]
Closing out due to age - if you still have an issue after waiting a day or two after installing, please open a new issue
