### ISSUE TITLE
Not showing next day pricing

### ISSUE THREAD

**Issue by bcfhex** [lozzd/octopus-energy-rates-card#52]
Using octopus-energy-rates-card v0.41 and the latest version of the Octopus Energy Integration I'm unable to see the next days prices (today's half hourly prices are been shown).

event.octopus_energy_electricity_19e50XXXXXX_14193084XXXXX_next_day_rates is enabled and populated.

my yaml for the card is as follows:

type: custom:octopus-energy-rates-card
currentEntity: event.octopus_energy_electricity_19e50XXXXX_14193084XXXXX_current_day_rates
futureEntity: event.octopus_energy_electricity_19e50XXXXX_14193084XXXXX_next_day_rates
targetTimesEntity: binary_sensor.octopus_energy_target_washing_machine_target
cols: 6
hour12: false
showday: true
showpast: false
title: Electric Price
unitstr: p
lowlimit: 7
mediumlimit: 20
highlimit: 27
roundUnits: 2
cheapest: true
multiplier: 100

Any ideas?
Many thanks

**Comment by riosil** [comment]
I experienced the same but noticed the Octopus Energy Integration didnot pick up the new rates today. I updated Octopus Energy to v9.2.0-Beta 2 and the rate card populated.

**Comment by bcfhex** [comment]
> I experienced the same but noticed the Octopus Energy Integration didnot pick up the new rates today. I updated Octopus Energy to v9.2.0-Beta 2 and the rate card populated.

Cheers, I've had a look at Bottle Cap Daves integration, I see they guys doing a lot of updates lately (#hero)

It actually eventually updated a few hours later, I'm sure it will all get sorted properly from what Ive been looking at on the betas.

**Comment by andymk3** [comment]
I am having this same problem. 

![EkpsMNW](https://github.com/lozzd/octopus-energy-rates-card/assets/26528265/244078cb-b190-4a40-8df0-c1231069f832)

Card config:

`type: custom:octopus-energy-rates-card
currentEntity: event.octopus_energy_electricity_19l2665096_2400000990219_current_day_rates
cols: 2
hour12: false
showday: true
showpast: false
title: Octopus Import
unitstr: p
lowlimit: 15
mediumlimit: 20
highlimit: 30
roundUnits: 2
cheapest: true
multiplier: 100
`

Running Octopus Energy 10.0.4 

Next day rates is working.

<img width="567" alt="image" src="https://github.com/lozzd/octopus-energy-rates-card/assets/26528265/2bd955b9-40a2-4662-bdd9-09c03ba69e0d">
