### ISSUE TITLE
Feature request: Make current timeslot font bold

### ISSUE THREAD

**Issue by josh-unwin** [lozzd/octopus-energy-rates-card#53]
I could have a go at doing this if you don't have capacity but think it'd be useful.

It'd be cool to highlight the current time slot in bold font.

**Comment by corvus2606** [comment]
I've managed to put a marker on the cyrrent timeslot:

<img width="490" alt="image" src="https://github.com/lozzd/octopus-energy-rates-card/assets/5789038/0313111a-682f-4de9-831b-43ef7778d898">

It's only visible if ShowPast is true

**Comment by lozzd** [comment]
Thanks @corvus2606  - Does it respect the colour scheme or is it always white? On my white background, I can't see it - can't tell if it's broken or just invisible

**Comment by pcb1962** [comment]
> is it always white?

Apparently not:
![image](https://github.com/lozzd/octopus-energy-rates-card/assets/5259660/f60b2ca1-6428-457b-80fb-8ee24998037c)

I'm pleased to se that there is no indicator if showpast is false.

**Comment by lozzd** [comment]
ah! That might be issue. I have mine configured to show the *current* time, but not past. Well, i'm glad it's working properly :) 

Will close this as it's live in v0.5.0. Thanks @corvus2606
