### ISSUE TITLE
I'm not getting it, is it me! - It was me

### ISSUE THREAD

**Issue by dougle03** [lozzd/octopus-energy-rates-card#56]
Been using HA for years and added the BottleTopDave HACE integration and moved onto Octopus Agile a few days ago.
I've installed the rate card and used the sample yaml as per below. 
But still I get the red error frame, what am I missing?

HA Current version; HACS Current version, Octopus Energy Current version

Screenshot:
![image](https://github.com/lozzd/octopus-energy-rates-card/assets/59865048/97267bef-e7c2-489d-ba6c-b38844024656)
yaml:
type: custom:octopus-energy-rates-card
currentEntity: event.octopus_energy_electricity_21l37XXXX_1100050XXXX_current_rate
cols: 2
hour12: false
showday: true
showpast: false
title: Octopus Import
unitstr: p
lowlimit: 15
mediumlimit: 20
highlimit: 30
roundUnits: 2
cheapest: true
multiplier: 100

States screenshot:
![image](https://github.com/lozzd/octopus-energy-rates-card/assets/59865048/9ea7fd9a-e2de-41a1-aa6b-f48a9060e7d7)

**Comment by anothermort** [comment]
The usual advice is simplify it as see if that works first.
I have this
![2023-12-25 09_06_45-Victron – Home Assistant — Mozilla Firefox](https://github.com/lozzd/octopus-energy-rates-card/assets/13786570/f69fa3c2-38dd-4aa3-b392-a4c9edd0aa6c)

**Comment by dougle03** [comment]
Ahh, always read ALL the instructions.... Seems that the events are not enabled by default when the Octopus integration is installed (Not sure why). I've enabled them all, so now waiting for them to 'enable' to see if that helps...

**Comment by dougle03** [comment]
So you have to enable the events in the main Octopus integration, they install disabled initially which is frustrating. Once enabled it takes a while for the rates to come in for the first time, give it a couple of hours before investigating further...
