### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by KashPopatErgosoft** [lozzd/octopus-energy-rates-card#66]
Hi, just upgraded to the latest version and now get:
![image](https://github.com/lozzd/octopus-energy-rates-card/assets/142222476/7d9a1b05-7161-4010-94c9-6f271d6c45e3)

Was working fine before update. Any ideas?

**Comment by lozzd** [comment]
@alinbalutoiu I am seeing the same (with no `targetTimesEntities` set) 
I'll unrelease v0.6.0 for a sec until fixed 
@KashPopatErgosoft can you roll back to v0.5.1 -

**Comment by Stephens-ely** [comment]
Same here - have had to uninstall and then put v0.5.1 back on.

**Comment by alinbalutoiu** [comment]
@lozzd I've just fixed it, sorry about that, missed it initially

**Comment by lozzd** [comment]
v0.6.0 deleted and v0.6.1 released - LGTM. Thanks for the quick reports & quick fix...
