### ISSUE TITLE
Advanced Configuration Options help

### ISSUE THREAD

**Issue by d1964b** [lozzd/octopus-energy-rates-card#68]
I Need some guidance on how to complete a 'Advanced Configuration' options in the yaml file .

1) **The option to specify backgroundColour**.  Is there a set of values we must select from for this ? If so what are they.
2) **The emoji prefixs**. Where have these come from, how do we enter them into the yaml?

Sorry if these are noddy questions,

**Comment by alinbalutoiu** [comment]
Hey there 👋 

For emojis, the OS has an integrated emoji keyboard, but probably the easiest option to copy them is to search it on Emojipedia https://emojipedia.org/

For the backgroundColour, you just need to pick a valid HTML color name, you can refer to this page for all possible options: https://www.w3schools.com/colors/colors_names.asp

**Comment by neildhunter** [comment]
Is there a trick to making this work in the new build? I can't even get it to apply the defaults for a single target sensor at the moment? Any hints on how to debug what the problem is?
