### ISSUE TITLE
targetTimesEntities works with Chrome but not Edge

### ISSUE THREAD

**Issue by ColinSainsbury** [lozzd/octopus-energy-rates-card#72]
Microsoft Edge Version 121.0.2277.128 (Official build) (64-bit) Windows 11 23H2 Feb 24 CU shows the cheapest 30 minute sections with navy blue when using targetTimesEntity but if I use targetTimesEntities there is no highlighting. The same code:
targetTimesEntities:
  binary_sensor.octopus_energy_target_powerwall:
    backgroundColour: navy
    prefix: 🔋
shows correctly in Google Chrome
![image](https://github.com/lozzd/octopus-energy-rates-card/assets/33755825/56a778ae-b7f0-4a84-b859-55e4fe058161)

but Edge shows 
![image](https://github.com/lozzd/octopus-energy-rates-card/assets/33755825/c883368f-5719-4927-972f-24a9d1979121)

Also shows correctly via HA Companion App on iOS

**Comment by alinbalutoiu** [comment]
There is no `targetTimesEntity` option so not sure what you're referring to here.

I just tried out my configuration in Microsoft Edge on my macbook and everything works as expected.

Could you share the console logs for edge in your case?

**Comment by alinbalutoiu** [comment]
Ah, just realised, that is the previous option.

It does sound like Edge is having some caching issues and not loading the latest version of the integration.

Do you still see the same in an incognito window? Try clearing your Edge browser cache

**Comment by ColinSainsbury** [comment]
Sorry, should have thought of the cache clear. All working now. Thanks

**Comment by ColinSainsbury** [comment]
Issue cache related
